name: Jazzy

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      run: echo ::set-env name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Echo version
      run: echo $VERSION
