# This is a basic workflow to help you get started with Actions

name: Jazzy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docs:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set version
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF#refs/*/}
    - name: Jazzy Docs
      run: |
        sudo gem install jazzy
        jazzy --module-version "$RELEASE_VERSION"
        git remote update
        git fetch origin gh-pages:gh-pages --depth 1
        git checkout gh-pages
        git config user.name  "Travis"
        git config user.email "jazzy@travis-ci.com"
        git add .
        git commit -m "Update documentation for $RELEASE_VERSION"
        git remote add secure-origin https://${{ secret.ACCESS_TOKEN }}@github.com/MyLibrary.git
        git push secure-origin gh-pages
