name: Jazzy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Echo version
      run: echo $VERSION
