name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
#     - name: Select Xcode
#       run: sudo xcode-select -switch /Applications/Xcode_12_beta.app
    - name: Xcode version
      run: /usr/bin/xcodebuild -version
    - name: Xcode build
      run: xcodebuild clean build -sdk iphoneos -scheme MyLibrary
